spring:
  application:
    name: chat-service
  r2dbc:
    url: r2dbc:h2:file:///./local.chat;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: password
  liquibase:
    url: jdbc:h2:file:./local.chat
    user: sa
    password: password
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
    database-change-log-table: chat_db_changelog
    database-change-log-lock-table: chat_db_changelog_lock
  webflux:
    apiversion:
      use:
        header: API-Version
      default: 1.0

server:
  port: 8081